import React, { useState, useEffect } from "react";
import { createClient } from "@/utils/supabase/client";
import AvatarComponent from "@/app/cproject/image";
import { IoMdEyeOff } from "react-icons/io";
import { IoEye } from "react-icons/io5";

export default function Maindata({
  compagny,
  name,
  country,
  city,
  lat,
  lng,
  cur,
  online,
  swim,
  closed,
  cctv,
  fenced,
  entrance,
  bike,
  disabled,
  child,
  fitness,
  user,
}) {
  const supabase = createClient();
  const [editableCompagny, setEditableCompagny] = useState(compagny);
  const [editableName, setEditableName] = useState(name);
  const [editableCountry, setEditableCountry] = useState(country);
  const [editableCity, setEditableCity] = useState(city);
  const [editableLat, setEditableLat] = useState(lat);
  const [editableLng, setEditableLng] = useState(lng);
  const [editableCurrency, setEditableCurrency] = useState(cur);
  const [isOnline, setIsOnline] = useState(online);
  const [features, setFeatures] = useState({
    swim,
    closed,
    cctv,
    fenced,
    entrance,
    bike,
    disabled,
    child,
    fitness,
  });
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    fetchProjects();
  }, []);

  const fetchProjects = async () => {
    const { data, error } = await supabase
      .from("project")
      .select(`*`)
      .eq("ide", user.id)
      .single();

    if (error) {
      console.error("Erreur lors de la récupération des projets :", error);
    } else {
      const project = data;
      setEditableCompagny(project.compagny);
      setEditableName(project.name);
      setEditableCountry(project.country);
      setEditableCity(project.city);
      setEditableLat(project.lat);
      setEditableLng(project.lng);
      setEditableCurrency(project.currency);
      setIsOnline(project.online);
      setFeatures({
        swim: project.swim,
        closed: project.closed,
        cctv: project.cctv,
        fenced: project.fenced,
        entrance: project.entrance,
        bike: project.bike,
        disabled: project.disabled,
        child: project.child,
        fitness: project.fitness,
      });
    }
  };

  const handleSave = async () => {
    setIsSaving(true);

    if (
      !editableCompagny ||
      !editableName ||
      !editableCountry ||
      !editableCity || // Ensure city is selected
      !editableLat ||
      !editableLng
    ) {
      alert("All fields, including the city, are required.");
      setIsSaving(false);
      return;
    }

    const { error } = await supabase
      .from("project")
      .update({
        compagny: editableCompagny,
        name: editableName,
        country: editableCountry,
        city: editableCity,
        lat: editableLat,
        lng: editableLng,
        currency: editableCurrency,
        online: isOnline,
        ...features,
      })
      .eq("ide", user.id);

    if (error) {
      console.error("Error saving data: ", error);
      alert("Failed to save data.");
    } else {
      alert("Data successfully saved.");
    }

    setIsSaving(false);
  };

  const toggleFeature = (feature) => {
    setFeatures((prevFeatures) => ({
      ...prevFeatures,
      [feature]: !prevFeatures[feature],
    }));
  };

  const countryData = {
    France: [
      "Paris",
      "Bordeaux",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Montpellier",
      "Strasbourg",
      "Lille",
      "Rennes",
      "Toulon",
      "Reims",
      "Saint-Étienne",
      "Le Havre",
      "Dijon",
      "Grenoble",
      "Angers",
      "Villeurbanne",
      "Nîmes",
      "Aix-en-Provence",
      "Clermont-Ferrand",
      "Le Mans",
      "Brest",
      "Tours",
      "Amiens",
      "Annecy",
      "Limoges",
      "Metz",
      "Boulogne-Billancourt",
      "Perpignan",
      "Besançon",
      "Orléans",
      "Rouen",
      "Saint-Denis",
      "Montreuil",
      "Caen",
      "Argenteuil",
      "Mulhouse",
      "Nancy",
      "Tourcoing",
      "Roubaix",
      "Nanterre",
      "Vitry-sur-Seine",
      "Créteil",
      "Poitiers",
      "Aubervilliers",
      "Colombes",
      "Dunkerque",
      "Aulnay-sous-Bois",
      "Versailles",
      "Courbevoic",
      "La Rochelle",
      "Rueil-Malmaison",
      "Champigny-sur-Marne",
      "Pau",
      "Mérignac",
      "Saint-Maur-des-Fossés",
      "Antibes",
      "Ajaccio",
      "Cannes",
      "Saint-Nazaire",
      "Drancy",
      "Noisy-le-Grand",
      "Issy-les-Moulineaux",
      "Cergy",
      "Levallois-Perret",
      "Calais",
      "Pessac",
      "Vénissieux",
      "Clichy",
      "Valence",
      "Ivry-sur-Seine",
      "Antony",
      "Troyes",
      "La Seyne-sur-Mer",
      "Pantin",
      "Chambéry",
      "Neuilly-sur-Seine",
      "Sarcelles",
      "Le Blanc-Mesnil",
      "Maisons-Alfort",
      "Lorient",
      "Villejuif",
      "Bellevue",
      "Beauvais",
      "Meaux",
      "Bobigny",
      "Clamart",
      "Vannes",
      "Chelles",
      "Évry",
      "Épinay-sur-Seine",
      "Saint-Ouen",
      "Saint-Quentin",
      "Bondy",
      "Bayonne",
      "Corbeil-Essonnes",
      "Cagnes-sur-Mer",
      "Vaulx-en-Velin",
      "Sevran",
      "Fontenay-sous-Bois",
      "Sartrouville",
      "Massy",
      "Laval",
      "Saint-Herblain",
      "Gennevilliers",
      "Suresnes",
      "Saint-Priest",
      "Vincennes",
      "Bastia",
      "Montrouge",
      "Évreux",
      "La Courneuve",
      "Charleville-Mézières",
      "Meudon",
      "Choisy-le-Roi",
      "Noisy-le-Sec",
      "Livry-Gargan",
      "Rosny-sous-Bois",
      "Talence",
      "Belfort",
      "Alfortville",
      "Chalon-sur-Saône",
      "Sète",
      "Mantes-la-Jolie",
      "Saint-Brieuc",
      "Tarbes",
      "Alès",
      "Châlons-en-Champagne",
      "Bagneux",
      "Puteaux",
      "Caluire-et-Cuire",
      "Bron",
      "Rezé",
      "Valenciennes",
      "Châteauroux",
      "Garges-lès-Gonesse",
      "Arras",
      "Melun",
      "Le Cannet",
      "Bourg-en-Bresse",
      "Anglet",
      "Angoulême",
      "Boulogne-sur-Mer",
      "Wattrelos",
      "Villenave-d’Ornon",
      "Stains",
      "Gagny",
      "Colomiers",
      "Poissy",
      "Douai",
      "Bagnolet",
      "Marcq-en-Baroeul",
      "Villepinte",
      "Saint-Martin-d’Hères",
      "Chartres",
      "Annemasse",
      "Neuilly-sur-Marne",
      "Franconville",
      "Savigny-sur-Orge",
      "Thonon-les-Bains",
      "Échirolles",
      "Châtillon",
      "Athis-Mons",
      "Creil",
      "Conflans-Sainte-Honorine",
      "Villefranche-sur-Saône",
      "Meyzieu",
      "Sainte-Geneviève-des-Bois",
      "Villeneuve-Saint-Georges",
      "Châtenay-Malabry",
      "Palaiseau",
      "Roanne",
      "Le Perreux-Sur-Marne",
      "Schiltigheim",
      "Les Mureaux",
      "Trappes",
      "Nogent-sur-Marne",
      "Houilles",
      "Montluçon",
      "Romainville",
      "Nevers",
      "Lens",
      "Agen",
      "Pierrefitte-sur-Seine",
      "Bezons",
      "Aix-les-Bains",
      "Montigny-le-Bretonneux",
      "Cambrai",
      "L’Haÿ-les-Roses",
      "Plaisir",
      "Pontoise",
      "Rillieux-la-Pape",
      "Thiais",
      "Vigneux-sur-Seine",
      "Viry-Châtillon",
      "Saint-Laurent-du-Var",
      "Bègles",
      "Goussainville",
      "Villiers-sur-Marne",
      "Cachan",
      "Savigny-le-Temple",
      "Menton",
      "Villemomble",
      "Malakoff",
      "Liévin",
      "La Garenne-Colombes",
      "Ris-Orangis",
      "Bois-Colombes",
      "Clichy-sous-Bois",
      "Décines-Charpieu",
      "Saint-Cloud",
      "Chatou",
      "Vandœuvre-lès-Nancy",
      "Périgueux",
      "Charenton-le-Pont",
      "Tournefeuille",
      "Guyancourt",
      "Le Plessis-Robinson",
      "Draveil",
      "Maubeuge",
      "Ermont",
      "Sotteville-lès-Rouen",
      "Villiers-le-Bel",
      "Fresnes",
      "Soissons",
      "Yerres",
      "Saint-Étienne-du-Rouvray",
      "Dieppe",
      "Saint-Sébastien-sur-Loire",
      "Vallauris",
      "Vanves",
      "Lomme",
      "Limeil-Brévannes",
      "Montfermeil",
      "Le Chesnay",
      "Sucy-en-Brie",
      "Grigny",
      "Lambersart",
      "Brétigny-sur-Orge",
      "Taverny",
      "Oullins",
      "Villeparisis",
      "Cenon",
      "Sannois",
      "Cormeilles-en-Parisis",
      "Bussy-Saint-Georges",
      "Blagnac",
      "Élancourt",
      "Le Grand-Quevilly",
      "La Garde",
      "Gradignan",
      "Vichy",
      "Biarritz",
      "Champs-Sur-Marne",
      "Armentières",
      "Montbéliard",
      "Alençon",
      "Brunoy",
      "Eaubonne",
      "Villeneuve-la-Garenne",
      "Cherbourg",
      "Saint-Ouen-l’Aumône",
      "Béthune",
      "Castelnau-le-Lez",
      "Fontenay-aux-Roses",
      "Orly",
      "Le Kremlin-Bicêtre",
      "Eysines",
      "Le Bouscat",
      "Rodez",
      "Les Pavillons-sous-Bois",
      "La Valette-du-Var",
      "Montgeron",
      "Les Lilas",
      "Lormont",
      "Maisons-Laffitte",
      "Roissy-en-Brie",
      "Loos",
      "Fontaine",
      "Dammarie-lè-Lys",
      "Vélizy-Villacoublay",
      "Tassin-la-Demi-Lune",
      "Sèvres",
      "Montigny-lès-Cormeilles",
      "Deuil-la-Barre",
      "La Madeleine",
      "Torcy",
      "Montereau-faut-Yonne",
      "Combs-la-Ville",
      "Hérouville-Saint-Clair",
      "Montmorency",
      "Sainte-Foy-lès-Lyon",
      "Montigny-lès-Metz",
      "Le Petit-Quevilly",
      "Saint-Jean-de-Braye",
      "Arcueil",
      "Mons-en-Baroeul",
      "Fleury-les-Aubrais",
      "Saint-Michel-sur-Orge",
      "Neuilly-Plaisance",
      "Nogent-sur-Oise",
      "Mantes-la-Ville",
      "Achères",
      "Saint-Mandé",
      "Villeneuve-le-Roi",
      "Saint-Cyr-l’École",
      "Saint-Genis-Laval",
      "Saint-Gratien",
      "Wasquehal",
      "Halluin",
      "Bourg-la-Reine",
      "Morsang-sur-Orge",
      "Croix",
      "Coudekerque-Branche",
      "Fougères",
      "Denain",
      "Longjumeau",
      "Sceaux",
      "Saint-Pol-sur-Mer",
      "La Celle-Saint-Cloud",
      "Joinville-le-Pont",
      "Cugnaux",
      "Chevilly-Larue",
      "Lingolsheim",
      "Le Plessis-Trévise",
      "Le Mée-sur-Seine",
      "Mont-Saint-Aignan",
      "Chaville",
      "Chilly-Mazarin",
      "Lisieux",
      "Ronchin",
      "Saint-Fons",
      "Moulins",
      "Villefontaine",
      "Gentilly",
      "Bonneuil-sur-Marne",
      "Hem",
      "Maurepas",
      "Meylan",
      "Éragny",
      "Hellemmes-Lille",
      "Juvisy-sur-Orge",
      "Chennevières-sur-Marne",
      "Écully",
      "Cran-Gévrier",
      "Carrières-sous-Poissy",
      "Rosendaël",
      "Fâches-Thumesnil",
      "Soisy-sous-Montmorency",
      "Bischheim",
      "Garches",
      "Hendaye",
      "Floirac",
      "Limay",
      "Boissy-Saint-Léger",
      "Le Pontet",
      "Chamalières",
      "Bry-sur-Marne",
      "Les Clayes-sous-Bois",
      "L’Isle-d’Abeau",
      "Jouy-le-Moutier",
      "Cluses",
      "Firminy",
      "Lons-le-Saunier",
      "Saint-Égrève",
      "Viroflay",
      "Octeville",
      "Le Pré-Saint-Gervais",
      "Saint-Jean-de-la-Ruelle",
      "Marly-le-Roi",
      "Domont",
      "Vauréal",
      "Orsay",
      "Saint-Leu-la-Forêt",
      "Verneuil-sur-Seine",
      "Petite-Synthe",
      "Saint-Julien-en-Genevois",
      "Le Pecq",
      "Le Vésinet",
      "Lucé",
      "Wattignies",
      "Noisiel",
      "Bois-d’Arcy",
      "Rive-de-Gier",
      "Saint-Brice-sous-Forêt",
      "Francheville",
      "Longwy",
      "Vesoul",
      "Montargis",
      "Carrières-sur-Seine",
      "Ramonville-Saint-Agne",
      "Castanet-Tolosan",
      "Le Raincy",
      "Le Bourget",
      "Illzach",
      "Montmagny",
      "Villers-lès-Nancy",
      "Haubourdin",
      "Dinan",
      "Lognes",
      "Saint-Maurice",
      "Verrières-le-Buisson",
      "Arnouville-lès-Gonesse",
      "Saint-Genis-Pouilly",
      "Les Sables-d’Olonne",
      "Montesson",
      "Valenton",
      "Chenôve",
      "Bois-Guillaume",
      "Auray",
      "Persan",
      "Fleury-Mérogis",
      "Audincourt",
      "Montévrain",
      "Billère",
      "Lys-lès-Lannoy",
      "Avon",
      "Vaires-sur-Marne",
      "Courcouronnes",
      "Fontenay-le-Fleury",
      "Anzin",
      "Ostwald",
      "Outreau",
      "Andrésy",
      "Morangis",
      "Kingersheim",
      "Mouvaux",
      "Saint-André",
      "Saint-André-les-Vergers",
      "Bayeux",
      "Beausoleil",
      "L’Union",
      "Bully-les-Mines",
      "Riedisheim",
      "Marly",
      "Craponne",
      "Talant",
      "Épinay-sous-Sénart",
      "Le Relecq-Kerhuon",
      "Villecresnes",
      "Hœnheim",
      "Vitry-le-François",
      "Enghien-les-Bains",
      "Méricourt",
      "Yvetot",
      "Dugny",
      "Bruay-sur-l’Escaut",
      "Saint-Germain-lès-Arpajon",
      "Arpajon",
      "Arcachon",
      "Saint-Jean",
      "Marquette-lès-Lille",
      "Cesson",
      "Stiring-Wendel",
      "Maromme",
      "Ferney-Voltaire",
      "Bondoufle",
      "Le Pont-de-Claix",
      "Épinay-sur-Orge",
      "Déville-lès-Rouen",
      "Chanteloup-les-Vignes",
      "Voisins-le-Bretonneux",
      "Ville-d’Avray",
      "Beaumont",
      "Flers-lez-Lille",
      "Tinqueux",
      "Ormesson-sur-Marne",
      "Pierre-Bénite",
      "Clermont",
      "Thorigny-sur-Marne",
      "Croissy-sur-Seine",
      "Villeneuve-Tolosane",
      "Avranches",
      "Pfastatt",
      "Igny",
      "Oignies",
      "Gaillard",
      "Neuville-en-Ferrain",
      "Caudebec-lès-Elbeuf",
      "Saint-Max",
      "Villerupt",
      "Auchel",
      "Vernouillet",
      "Aniche",
      "Eybens",
      "Fosses",
      "Maxéville",
      "Montigny-en-Gohelle",
      "Grigny",
      "Darnétal",
      "Serris",
      "Sallaumines",
      "Neuville-lès-Dieppe",
      "Beaumont-sur-Oise",
      "Leers",
      "Ézanville",
      "Pérols",
      "Crosne",
      "Quincy-sous-Sénart",
      "Jarville-la-Malgrange",
      "Aucamville",
      "Hagondange",
      "Le Crès",
      "Bures-sur-Yvette",
      "Évian-les-Bains",
      "Ville-la-Grand",
      "Beauchamp",
      "Magny-le-Hongre",
      "Bougival",
      "Tomblaine",
      "Le Portel",
      "Fontaine-lès-Dijon",
      "Boucau",
      "Essey-lès-Nancy",
      "Wingles",
      "Montlhéry",
      "L’Île-Saint-Denis",
      "Vaucresson",
      "La Salvetat-Saint-Gilles",
      "Pérenchies",
      "Saint-Aubin-lès-Elbeuf",
      "Groslay",
      "Le Plessis-Bouchard",
      "Meythet",
      "Terrenoire",
      "Harfleur",
      "Carbon-Blanc",
      "Courcelles-les-Lens",
      "Bihorel",
      "La Tour-du-Pin",
      "Souffelweyersheim",
      "Billy-Montigny",
      "La Ville-du-Bois",
      "Coulaines",
      "Boussy-Saint-Antoine",
      "Le Mesnil-Esnard",
      "Talange",
      "Cappelle-la-Grande",
      "Beauzelle",
      "Vaujours",
      "Saint-Germain-lès-Corbeil",
      "Terville",
      "Waziers",
      "Huningue",
      "Villemoisson-sur-Orge",
      "Sainte-Adresse",
      "Guingamp",
      "Fontaines-sur-Saône",
      "Liancourt",
      "Courtry",
      "Gournay-sur-Marne",
      "Sathonay-Camp",
      "Jacou",
      "Beuvrages",
      "Égly",
      "Carnoux-en-Provence",
      "Grenay",
      "Luisant",
      "Noyelles-sous-Lens",
      "La Bassée",
      "Neuves-Maisons",
      "La Mulatière",
      "Bouffémont",
      "La Penne-sur-Huveaune",
      "Jœuf",
      "Cognin",
      "La Montagne",
      "Bonsecours",
      "Saint-Alban",
      "L’Arbresle",
      "Esbly",
      "Le Mesnil-le-Roi",
      "Fouquières-lès-Lens",
      "La Verrière",
      "Ambilly",
      "Saint-Priest-en-Jarez",
      "Magnanville",
      "Pont-de-Chéruy",
      "Menucourt",
      "Ablon-sur-Seine",
      "Champagne-au-Mont-d’Or",
      "Palavas-les-Flots",
      "Saintry-sur-Seine",
      "Saint-André-de-la-Roche",
      "Longueau",
      "Le Port-Marly",
      "Oberhausbergen",
      "Heillecourt",
      "Crégy-lès-Meaux",
      "Loison-sous-Lens",
      "Montaigu",
      "Bassens",
      "Grand-Fort-Philippe",
      "Mandres-les-Roses",
      "La Frette-sur-Seine",
      "Le Ban-Saint-Martin",
      "Saint-Nicolas",
      "Villiers-sur-Orge",
      "Cap-d’Ail",
      "Nilvange",
      "Leuville-sur-Orge",
      "Jacob-Bellecombette",
      "Valras-Plage",
      "Avesnes-sur-Helpe",
      "Ascq",
      "Longeville-lès-Metz",
      "Neuville-Saint-Rémy",
      "Toufflers",
      "Mareil-Marly",
      "Lourches",
      "Beaulieu-sur-Mer",
      "Sochaux",
      "Bergues",
      "Barby",
      "Fort-Mardyck",
      "Neauphle-le-Château",
      "Saint-Mammès",
      "Les Noës-près-Troyes",
      "Pont-à-Vendin",
      "Rouelles",
      "Paimbœuf",
      "Courchelettes",
      "Éleu-dit-Leauwette",
      "Port-Louis",
      "Sainte-Foy-la-Grande",
    ],
    Poland: [
      "Aleksandrów Kujawski",
      "Aleksandrów Łódzki",
      "Alwernia",
      "Andrychów",
      "Annopol",
      "Augustów",
      "Babimost",
      "Baborów",
      "Baranów Sandomierski",
      "Barcin",
      "Barczewo",
      "Bardo",
      "Barlinek",
      "Bartoszyce",
      "Barwice",
      "Bełchatów",
      "Bełżyce",
      "Biała",
      "Biała Piska",
      "Biała Podlaska",
      "Biała Rawska",
      "Białobrzegi",
      "Białogard",
      "Biały Bór",
      "Białystok",
      "Biecz",
      "Bielawa",
      "Bielsk Podlaski",
      "Bielsko-Biała",
      "Bierutów",
      "Bieruń",
      "Bieżuń",
      "Biskupiec",
      "Bisztynek",
      "Biłgoraj",
      "Blachownia",
      "Bobolice",
      "Bobowa",
      "Bochnia",
      "Bodzentyn",
      "Bogatynia",
      "Boguchwała",
      "Boguszów-Gorce",
      "Bojanowo",
      "Bolesławiec",
      "Bolków",
      "Borek Wielkopolski",
      "Borne Sulinowo",
      "Braniewo",
      "Brańsk",
      "Brodnica",
      "Brok",
      "Brusy",
      "Brwinów",
      "Brzeg",
      "Brzeg Dolny",
      "Brzesko",
      "Brzeszcze",
      "Brzeziny",
      "Brześć Kujawski",
      "Brzostek",
      "Brzozów",
      "Buk",
      "Bukowno",
      "Busko-Zdrój",
      "Bychawa",
      "Byczyna",
      "Bydgoszcz",
      "Bystrzyca Kłodzka",
      "Bytom",
      "Bytom Odrzański",
      "Bytów",
      "Będzin",
      "Błaszki",
      "Błażowa",
      "Błonie",
      "Cedynia",
      "Chełm",
      "Chełmek",
      "Chełmno",
      "Chełmża",
      "Chmielnik",
      "Chocianów",
      "Chociwel",
      "Chocz",
      "Chodecz",
      "Chodzież",
      "Chojna",
      "Chojnice",
      "Chojnów",
      "Choroszcz",
      "Chorzele",
      "Chorzów",
      "Choszczno",
      "Chrzanów",
      "Chęciny",
      "Ciechanowiec",
      "Ciechanów",
      "Ciechocinek",
      "Cieszanów",
      "Cieszyn",
      "Ciężkowice",
      "Cybinka",
      "Czaplinek",
      "Czarna Białostocka",
      "Czarna Woda",
      "Czarne",
      "Czarnków",
      "Czchów",
      "Czechowice-Dziedzice",
      "Czeladź",
      "Czempiń",
      "Czerniejewo",
      "Czersk",
      "Czerwieńsk",
      "Czerwionka-Leszczyny",
      "Czyżew",
      "Częstochowa",
      "Człopa",
      "Człuchów",
      "Daleszyce",
      "Darłowo",
      "Debrzno",
      "Dobczyce",
      "Dobiegniew",
      "Dobra (powiat turecki)",
      "Dobra (powiat łobeski)",
      "Dobre Miasto",
      "Dobrodzień",
      "Dobrzany",
      "Dobrzyca",
      "Dobrzyń nad Wisłą",
      "Dolsk",
      "Drawno",
      "Drawsko Pomorskie",
      "Drezdenko",
      "Drobin",
      "Drohiczyn",
      "Drzewica",
      "Dukla",
      "Duszniki-Zdrój",
      "Dynów",
      "Działdowo",
      "Działoszyce",
      "Działoszyn",
      "Dzierzgoń",
      "Dzierżoniów",
      "Dziwnów",
      "Dąbie",
      "Dąbrowa Białostocka",
      "Dąbrowa Górnicza",
      "Dąbrowa Tarnowska",
      "Dębica",
      "Dęblin",
      "Dębno",
      "Elbląg",
      "Ełk",
      "Frampol",
      "Frombork",
      "Garwolin",
      "Gdańsk",
      "Gdynia",
      "Giżycko",
      "Glinojeck",
      "Gliwice",
      "Gniew",
      "Gniewkowo",
      "Gniezno",
      "Gogolin",
      "Golczewo",
      "Goleniów",
      "Golina",
      "Golub-Dobrzyń",
      "Goniądz",
      "Gorlice",
      "Gorzów Wielkopolski",
      "Gorzów Śląski",
      "Gostynin",
      "Gostyń",
      "Gozdnica",
      "Gołańcz",
      "Gołdap",
      "Gościno",
      "Grabów nad Prosną",
      "Grajewo",
      "Grodków",
      "Grodzisk Mazowiecki",
      "Grodzisk Wielkopolski",
      "Grudziądz",
      "Grybów",
      "Gryfice",
      "Gryfino",
      "Gryfów Śląski",
      "Grójec",
      "Gubin",
      "Góra",
      "Góra Kalwaria",
      "Górowo Iławeckie",
      "Górzno",
      "Gąbin",
      "Głogów",
      "Głogów Małopolski",
      "Głogówek",
      "Głowno",
      "Głubczyce",
      "Głuchołazy",
      "Głuszyca",
      "Główny dworzec kolejowy",
      "Hajnówka",
      "Halinów",
      "Hel",
      "Hrubieszów",
      "Imielin",
      "Inowrocław",
      "Iwonicz-Zdrój",
      "Izbica Kujawska",
      "Iława",
      "Iłowa",
      "Iłża",
      "Ińsko",
      "Jabłonowo Pomorskie",
      "Janikowo",
      "Janowiec Wielkopolski",
      "Janów Lubelski",
      "Jaraczewo",
      "Jarocin",
      "Jarosław",
      "Jasień",
      "Jastarnia",
      "Jastrowie",
      "Jastrzębie-Zdrój",
      "Jasło",
      "Jawor",
      "Jaworzno",
      "Jaworzyna Śląska",
      "Jedlicze",
      "Jedlina-Zdrój",
      "Jedwabne",
      "Jelcz-Laskowice",
      "Jelenia Góra",
      "Jeziorany",
      "Jordanów",
      "Jutrosin",
      "Józefów (powiat biłgorajski)",
      "Józefów (powiat otwocki)",
      "Józefów nad Wisłą",
      "Jędrzejów",
      "Kalety",
      "Kalisz",
      "Kalisz Pomorski",
      "Kalwaria Zebrzydowska",
      "Kamienna Góra",
      "Kamień Krajeński",
      "Kamień Pomorski",
      "Kamieńsk",
      "Karczew",
      "Kargowa",
      "Karlino",
      "Karpacz",
      "Kartuzy",
      "Katowice",
      "Kazimierz Dolny",
      "Kazimierza Wielka",
      "Kałuszyn",
      "Kańczuga",
      "Kcynia",
      "Kielce",
      "Kietrz",
      "Kisielice",
      "Kleczew",
      "Kleszczele",
      "Kluczbork",
      "Knurów",
      "Knyszyn",
      "Kobylin",
      "Kobyłka",
      "Kock",
      "Kolbuszowa",
      "Kolno",
      "Kolonowskie",
      "Koluszki",
      "Koniecpol",
      "Konin",
      "Konstancin-Jeziorna",
      "Konstantynów Łódzki",
      "Koprzywnica",
      "Korfantów",
      "Koronowo",
      "Korsze",
      "Kostrzyn",
      "Kostrzyn nad Odrą",
      "Koszalin",
      "Koszyce",
      "Kosów Lacki",
      "Kowal",
      "Kowalewo Pomorskie",
      "Kowary",
      "Koziegłowy",
      "Kozienice",
      "Kołaczyce",
      "Koło",
      "Kołobrzeg",
      "Końskie",
      "Kościan",
      "Kościerzyna",
      "Koźmin Wielkopolski",
      "Kożuchów",
      "Krajenka",
      "Kraków",
      "Krapkowice",
      "Krasnobród",
      "Krasnystaw",
      "Kraśnik",
      "Krobia",
      "Krosno",
      "Krosno Odrzańskie",
      "Krotoszyn",
      "Krośniewice",
      "Kruszwica",
      "Krynica Morska",
      "Krynica-Zdrój",
      "Krynki",
      "Krzanowice",
      "Krzepice",
      "Krzeszowice",
      "Krzywiń",
      "Krzyż Wielkopolski",
      "Książ Wielkopolski",
      "Kudowa-Zdrój",
      "Kunów",
      "Kutno",
      "Kuźnia Raciborska",
      "Kwidzyn",
      "Kórnik",
      "Kąty Wrocławskie",
      "Kędzierzyn-Koźle",
      "Kępice",
      "Kępno",
      "Kętrzyn",
      "Kęty",
      "Kłecko",
      "Kłobuck",
      "Kłodawa",
      "Kłodzko",
      "Legionowo",
      "Legnica",
      "Lesko",
      "Leszno",
      "Lewin Brzeski",
      "Leśna",
      "Leśnica",
      "Leżajsk",
      "Libiąż",
      "Lidzbark",
      "Lidzbark Warmiński",
      "Limanowa",
      "Lipiany",
      "Lipno",
      "Lipsk",
      "Lipsko",
      "Lubaczów",
      "Lubartów",
      "Lubawa",
      "Lubawka",
      "Lubań",
      "Lubień Kujawski",
      "Lubin",
      "Lublin",
      "Lubliniec",
      "Lubniewice",
      "Lubomierz",
      "Lubowidz",
      "Luboń",
      "Lubraniec",
      "Lubsko",
      "Lubycza Królewska",
      "Lwówek",
      "Lwówek Śląski",
      "Lądek-Zdrój",
      "Lębork",
      "Lędziny",
      "Maków Mazowiecki",
      "Maków Podhalański",
      "Malbork",
      "Margonin",
      "Marki",
      "Maszewo",
      "Małogoszcz",
      "Małomice",
      "Miasteczko Śląskie",
      "Miastko",
      "Michałowo",
      "Miechów",
      "Miejska Górka",
      "Mielec",
      "Mielno",
      "Mieroszów",
      "Mieszkowice",
      "Mikołajki",
      "Mikołów",
      "Mikstat",
      "Milanówek",
      "Milicz",
      "Mirosławiec",
      "Mirsk",
      "Międzybórz",
      "Międzychód",
      "Międzylesie",
      "Międzyrzec Podlaski",
      "Międzyrzecz",
      "Międzyzdroje",
      "Miłakowo",
      "Miłomłyn",
      "Miłosław",
      "Mińsk Mazowiecki",
      "Modliborzyce",
      "Mogielnica",
      "Mogilno",
      "Morawica",
      "Mordy",
      "Moryń",
      "Morąg",
      "Mosina",
      "Mońki",
      "Mrocza",
      "Mrozy",
      "Mrągowo",
      "Mszana Dolna",
      "Mszczonów",
      "Murowana Goślina",
      "Muszyna",
      "Myszków",
      "Myszyniec",
      "Mysłowice",
      "Myślenice",
      "Myślibórz",
      "Mława",
      "Młynary",
      "Nakło nad Notecią",
      "Namysłów",
      "Narol",
      "Nasielsk",
      "Nałęczów",
      "Nekla",
      "Nidzica",
      "Niemcza",
      "Niemodlin",
      "Niepołomice",
      "Nieszawa",
      "Nisko",
      "Nowa Dęba",
      "Nowa Ruda",
      "Nowa Sarzyna",
      "Nowa Sól",
      "Nowa Słupia",
      "Nowe",
      "Nowe Brzesko",
      "Nowe Miasteczko",
      "Nowe Miasto Lubawskie",
      "Nowe Miasto nad Pilicą",
      "Nowe Skalmierzyce",
      "Nowe Warpno",
      "Nowogard",
      "Nowogrodziec",
      "Nowogród",
      "Nowogród Bobrzański",
      "Nowy Dwór Gdański",
      "Nowy Dwór Mazowiecki",
      "Nowy Korczyn",
      "Nowy Staw",
      "Nowy Sącz",
      "Nowy Targ",
      "Nowy Tomyśl",
      "Nowy Wiśnicz",
      "Nysa",
      "Oborniki",
      "Oborniki Śląskie",
      "Obrzycko",
      "Odolanów",
      "Ogrodzieniec",
      "Okonek",
      "Olecko",
      "Olesno",
      "Oleszyce",
      "Oleśnica",
      "Oleśnica",
      "Olkusz",
      "Olsztyn",
      "Olsztynek",
      "Olszyna",
      "Opalenica",
      "Opatowiec",
      "Opatów",
      "Opatówek",
      "Opoczno",
      "Opole",
      "Opole Lubelskie",
      "Orneta",
      "Orzesze",
      "Orzysz",
      "Osieczna",
      "Osiek",
      "Ostroróg",
      "Ostrowiec Świętokrzyski",
      "Ostrołęka",
      "Ostrzeszów",
      "Ostróda",
      "Ostrów Lubelski",
      "Ostrów Mazowiecka",
      "Ostrów Wielkopolski",
      "Otmuchów",
      "Otwock",
      "Otyń",
      "Ozimek",
      "Ozorków",
      "Oława",
      "Ośno Lubuskie",
      "Oświęcim",
      "Ożarów",
      "Ożarów Mazowiecki",
      "Pabianice",
      "Pacanów",
      "Paczków",
      "Pajęczno",
      "Pakość",
      "Parczew",
      "Pasym",
      "Pasłęk",
      "Pelplin",
      "Pełczyce",
      "Piaseczno",
      "Piaski",
      "Piastów",
      "Piechowice",
      "Piekary Śląskie",
      "Pieniężno",
      "Pierzchnica",
      "Pieszyce",
      "Pieńsk",
      "Pilawa",
      "Pilica",
      "Pilzno",
      "Pionki",
      "Piotrków Kujawski",
      "Piotrków Trybunalski",
      "Pisz",
      "Piwniczna-Zdrój",
      "Piła",
      "Piława Górna",
      "Pińczów",
      "Pleszew",
      "Pniewy",
      "Pobiedziska",
      "Poddębice",
      "Podkowa Leśna",
      "Pogorzela",
      "Polanica-Zdrój",
      "Polanów",
      "Police",
      "Polkowice",
      "Poniatowa",
      "Poniec",
      "Poręba",
      "Poznań",
      "Połaniec",
      "Połczyn-Zdrój",
      "Prabuty",
      "Praszka",
      "Prochowice",
      "Proszowice",
      "Pruchnik",
      "Prudnik",
      "Prusice",
      "Pruszcz Gdański",
      "Pruszków",
      "Przasnysz",
      "Przecław",
      "Przedbórz",
      "Przedecz",
      "Przemków",
      "Przemyśl",
      "Przeworsk",
      "Przysucha",
      "Prószków",
      "Pszczyna",
      "Pszów",
      "Puck",
      "Puszczykowo",
      "Puławy",
      "Pułtusk",
      "Pyrzyce",
      "Pyskowice",
      "Pyzdry",
      "Płock",
      "Płoty",
      "Płońsk",
      "Rabka-Zdrój",
      "Racibórz",
      "Raciąż",
      "Radków",
      "Radlin",
      "Radom",
      "Radomsko",
      "Radomyśl Wielki",
      "Radoszyce",
      "Radymno",
      "Radziejów",
      "Radzionków",
      "Radzymin",
      "Radzyń Chełmiński",
      "Radzyń Podlaski",
      "Radłów",
      "Rajgród",
      "Rakoniewice",
      "Raszków",
      "Ratusz",
      "Ratusz",
      "Rawa Mazowiecka",
      "Rawicz",
      "Recz",
      "Reda",
      "Rejowiec",
      "Rejowiec Fabryczny",
      "Resko",
      "Reszel",
      "Rogoźno",
      "Ropczyce",
      "Ruciane-Nida",
      "Ruda Śląska",
      "Rudnik nad Sanem",
      "Rumia",
      "Rybnik",
      "Rychwał",
      "Rydułtowy",
      "Rydzyna",
      "Ryglice",
      "Ryki",
      "Rymanów",
      "Ryn",
      "Rypin",
      "Rzepin",
      "Rzeszów",
      "Rzgów",
      "Różan",
      "Sandomierz",
      "Sanniki",
      "Sanok",
      "Sejny",
      "Serock",
      "Sianów",
      "Siechnice",
      "Siedlce",
      "Siedliszcze",
      "Siemianowice Śląskie",
      "Siemiatycze",
      "Sieniawa",
      "Sieradz",
      "Sieraków",
      "Sierpc",
      "Siewierz",
      "Skalbmierz",
      "Skarszewy",
      "Skaryszew",
      "Skarżysko-Kamienna",
      "Skawina",
      "Skała",
      "Skierniewice",
      "Skoczów",
      "Skoki",
      "Skwierzyna",
      "Skórcz",
      "Skępe",
      "Sobótka",
      "Sochaczew",
      "Sokołów Małopolski",
      "Sokołów Podlaski",
      "Sokółka",
      "Solec Kujawski",
      "Sompolno",
      "Sopot",
      "Sosnowiec",
      "Sośnicowice",
      "Stalowa Wola",
      "Starachowice",
      "Stargard",
      "Starogard Gdański",
      "Stary Sącz",
      "Staszów",
      "Stawiski",
      "Stawiszyn",
      "Stepnica",
      "Stoczek Łukowski",
      "Stopnica",
      "Stronie Śląskie",
      "Strumień",
      "Stryków",
      "Strzegom",
      "Strzelce Krajeńskie",
      "Strzelce Opolskie",
      "Strzelin",
      "Strzelno",
      "Strzyżów",
      "Stąporków",
      "Stęszew",
      "Sucha Beskidzka",
      "Suchań",
      "Suchedniów",
      "Suchowola",
      "Sulechów",
      "Sulejów",
      "Sulejówek",
      "Sulmierzyce",
      "Sulęcin",
      "Supraśl",
      "Suraż",
      "Susz",
      "Suwałki",
      "Sułkowice",
      "Swarzędz",
      "Syców",
      "Szadek",
      "Szamocin",
      "Szamotuły",
      "Szczawnica",
      "Szczawno-Zdrój",
      "Szczebrzeszyn",
      "Szczecin",
      "Szczecinek",
      "Szczekociny",
      "Szczucin",
      "Szczuczyn",
      "Szczyrk",
      "Szczytna",
      "Szczytno",
      "Szepietowo",
      "Szklarska Poręba",
      "Szlichtyngowa",
      "Szprotawa",
      "Sztum",
      "Szubin",
      "Szydłowiec",
      "Szydłów",
      "Sędziszów",
      "Sędziszów Małopolski",
      "Sępopol",
      "Sępólno Krajeńskie",
      "Sława",
      "Sławków",
      "Sławno",
      "Słomniki",
      "Słubice",
      "Słupca",
      "Słupsk",
      "Tarczyn",
      "Tarnobrzeg",
      "Tarnogród",
      "Tarnowskie Góry",
      "Tarnów",
      "Tczew",
      "Terespol",
      "Tolkmicko",
      "Tomaszów Lubelski",
      "Tomaszów Mazowiecki",
      "Toruń",
      "Torzym",
      "Toszek",
      "Trzcianka",
      "Trzciel",
      "Trzcińsko-Zdrój",
      "Trzebiatów",
      "Trzebinia",
      "Trzebnica",
      "Trzemeszno",
      "Tuchola",
      "Tuchów",
      "Tuczno",
      "Tuliszków",
      "Turek",
      "Tuszyn",
      "Tułowice",
      "Twardogóra",
      "Tychowo",
      "Tychy",
      "Tyczyn",
      "Tykocin",
      "Tyszowce",
      "Tłuszcz",
      "Ujazd",
      "Ujście",
      "Ulanów",
      "Uniejów",
      "Urzędów",
      "Ustka",
      "Ustroń",
      "Ustrzyki Dolne",
      "Wadowice",
      "Warka",
      "Warszawa",
      "Warta",
      "Wasilków",
      "Wałbrzych",
      "Wałcz",
      "Wejherowo",
      "Wielbark",
      "Wieleń",
      "Wielichowo",
      "Wieliczka",
      "Wieluń",
      "Wieruszów",
      "Wilamowice",
      "Wisła",
      "Witkowo",
      "Witnica",
      "Wiązów",
      "Więcbork",
      "Wiślica",
      "Wleń",
      "Wodzisław Śląski",
      "Wojcieszów",
      "Wojkowice",
      "Wojnicz",
      "Wolbrom",
      "Wolbórz",
      "Wolin",
      "Wolsztyn",
      "Wołczyn",
      "Wołomin",
      "Wołów",
      "Woźniki",
      "Wrocław",
      "Wronki",
      "Września",
      "Wschowa",
      "Wyrzysk",
      "Wysoka",
      "Wysokie Mazowieckie",
      "Wyszków",
      "Wyszogród",
      "Wyśmierzyce",
      "Wąbrzeźno",
      "Wąchock",
      "Wągrowiec",
      "Wąsosz",
      "Węgliniec",
      "Węgorzewo",
      "Węgorzyno",
      "Węgrów",
      "Władysławowo",
      "Włocławek",
      "Włodawa",
      "Włoszczowa",
      "Zabrze",
      "Zabłudów",
      "Zagórz",
      "Zagórów",
      "Zakliczyn",
      "Zaklików",
      "Zakopane",
      "Zakroczym",
      "Zalewo",
      "Zambrów",
      "Zamość",
      "Zator",
      "Zawadzkie",
      "Zawichost",
      "Zawidów",
      "Zawiercie",
      "Zbąszynek",
      "Zbąszyń",
      "Zduny",
      "Zduńska Wola",
      "Zdzieszowice",
      "Zelów",
      "Zgierz",
      "Zgorzelec",
      "Zielona Góra",
      "Zielonka",
      "Ziębice",
      "Zwierzyniec",
      "Zwoleń",
      "Ząbki",
      "Ząbkowice Śląskie",
      "Złocieniec",
      "Złoczew",
      "Złotoryja",
      "Złoty Stok",
      "Złotów",
      "Ćmielów",
      "Łabiszyn",
      "Łagów",
      "Łapy",
      "Łasin",
      "Łask",
      "Łaskarzew",
      "Łaszczów",
      "Łaziska Górne",
      "Łazy",
      "Łańcut",
      "Łeba",
      "Łobez",
      "Łobżenica",
      "Łochów",
      "Łomianki",
      "Łomża",
      "Łosice",
      "Łowicz",
      "Łuków",
      "Łódź",
      "Łęczna",
      "Łęczyca",
      "Łęknica",
      "Ścinawa",
      "Ślesin",
      "Śmigiel",
      "Śrem",
      "Środa Wielkopolska",
      "Środa Śląska",
      "Świdnica",
      "Świdnik",
      "Świdwin",
      "Świebodzice",
      "Świebodzin",
      "Świecie",
      "Świeradów-Zdrój",
      "Świerzawa",
      "Świnoujście",
      "Świątniki Górne",
      "Świętochłowice",
      "Żabno",
      "Żagań",
      "Żarki",
      "Żary",
      "Żarów",
      "Żelechów",
      "Żerków",
      "Żmigród",
      "Żnin",
      "Żory",
      "Żukowo",
      "Żuromin",
      "Żychlin",
      "Żyrardów",
      "Żywiec",
    ],
  };

  const CountryCitySelector = ({
    editableCountry,
    setEditableCountry,
    editableCity,
    setEditableCity,
  }) => {
    const [cities, setCities] = useState([]);

    useEffect(() => {
      if (editableCountry && countryData[editableCountry]) {
        setCities(countryData[editableCountry]);
      } else {
        setCities([]);
      }
    }, [editableCountry]);

    const handleCountryChange = (e) => {
      const selectedCountry = e.target.value;
      setEditableCountry(selectedCountry);

      // Ensure city is cleared when switching countries
      if (countryData[selectedCountry]) {
        setEditableCity(countryData[selectedCountry][0]);
      } else {
        setEditableCity("");
      }
    };

    const handleCityChange = (e) => {
      setEditableCity(e.target.value);
    };

    return (
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-4 text-white">
        <div className="flex flex-col">
          <label className="text-white mb-1">Country</label>
          <select
            value={editableCountry}
            onChange={handleCountryChange}
            className="border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
          >
            <option value="">Select a country</option>
            {Object.keys(countryData).map((country) => (
              <option key={country} value={country}>
                {country}
              </option>
            ))}
          </select>
        </div>

        <div className="flex flex-col ">
          <label className="text-white mb-1">City</label>
          <select
            value={editableCity}
            onChange={handleCityChange}
            className="border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
            disabled={!editableCountry}
          >
            <option value="">Select a city</option>
            {cities.map((city) => (
              <option key={city} value={city}>
                {city}
              </option>
            ))}
          </select>
        </div>
      </div>
    );
  };

  return (
    <div className="mx-auto mt-10 p-6 bg-[#12171E] rounded-lg shadow-xl flex flex-col justify-center items-center mb-8 text-white">
      <div className="mb-8">
        <AvatarComponent user={user} />
      </div>
      <h2 className="text-2xl font-semibold text-white mb-4">
        Edit Project Information
      </h2>
      <div className="flex gap-8">
        <div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-white">
            <div className="flex flex-col mb-4">
              <label className="text-white mb-1">Company</label>
              <input
                type="text"
                value={editableCompagny}
                onChange={(e) => setEditableCompagny(e.target.value)}
                className="border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
              />
            </div>
            <div className="flex flex-col">
              <label className="text-white mb-1">Project Name</label>
              <input
                type="text"
                value={editableName}
                onChange={(e) => setEditableName(e.target.value)}
                className="border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
              />
            </div>
            </div>
            <div className="">
              <CountryCitySelector
                editableCountry={editableCountry}
                setEditableCountry={setEditableCountry}
                editableCity={editableCity}
                setEditableCity={setEditableCity}
              />
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-white">
            <div className="flex flex-col">
              <label className="text-white mb-1">Latitude</label>
              <input
                type="text"
                value={editableLat}
                onChange={(e) => setEditableLat(e.target.value)}
                className="border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
              />
            </div>
            <div className="flex flex-col">
              <label className="text-white mb-1">Longitude</label>
              <input
                type="text"
                value={editableLng}
                onChange={(e) => setEditableLng(e.target.value)}
                className="border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
              />
            </div>
            <div className="flex flex-col">
              <label className="text-white mb-1">Currency</label>
              <select
                value={editableCurrency}
                onChange={(e) => setEditableCurrency(e.target.value)}
                className="border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
              >
                <option value="EUR">Euro (EUR)</option>
                <option value="PLN">Polish Zloty (PLN)</option>
              </select>
            </div>

            
       
            <div className="flex flex-col">
              <label className="text-white mb-1 flex">
                Your project is
                <span className="text-white flex items-center">
                  <span className="ml-2">
                    {isOnline ? "Online" : "Offline"}
                  </span>
                  {isOnline ? (
                    <IoEye className="ml-2 text-xl text-green-600" />
                  ) : (
                    <IoMdEyeOff className="ml-2 text-xl text-red-600" />
                  )}
                </span>
              </label>
              <div className="relative flex items-center">
                <input
                  type="checkbox"
                  id="onlineSwitch"
                  checked={isOnline}
                  onChange={() => setIsOnline(!isOnline)}
                  className="hidden"
                />
                <label
                  htmlFor="onlineSwitch"
                  className="flex items-center cursor-pointer"
                  aria-label="Toggle project online status"
                >
                  <div
                    className={`w-10 h-6 flex items-center rounded-full p-1 ${
                      isOnline ? "bg-green-500" : "bg-red-600"
                    }`}
                  >
                    <div
                      className={`w-4 h-4 bg-white rounded-full shadow-md transform transition-transform ${
                        isOnline ? "translate-x-4" : "translate-x-0"
                      }`}
                    />
                  </div>
                </label>
                </div>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          {Object.keys(features).map((feature) => (
            <div className="relative flex items-center pr-12" key={feature}>
              <input
                type="checkbox"
                id={`${feature}Switch`}
                checked={features[feature]}
                onChange={() => toggleFeature(feature)}
                className="hidden"
              />
              <label
                htmlFor={`${feature}Switch`}
                className="flex items-center cursor-pointer"
                aria-label={`Toggle ${feature} feature`}
              >
                <div
                  className={`w-10 h-6 flex items-center rounded-full p-1 ${
                    features[feature] ? "bg-blue-500" : "bg-gray-600"
                  }`}
                >
                  <div
                    className={`w-4 h-4 bg-white rounded-full shadow-md transform transition-transform ${
                      features[feature] ? "translate-x-4" : "translate-x-0"
                    }`}
                  />
                </div>
                <p className="ml-2 capitalize">{feature}</p>
              </label>
            </div>
          ))}
        </div>
      </div>
      <button
        onClick={handleSave}
        className={`mt-8 bg-blue-500 text-white px-6 py-2 rounded-md ${
          isSaving ? "opacity-50 cursor-not-allowed" : ""
        }`}
        disabled={isSaving}
      >
        {isSaving ? "Saving..." : "Save Changes"}
      </button>
    </div>
  );
}
