import { select } from "@heroui/react";
import { on } from "events";





export const texts = {
    fr: {
        link: "Voir tous les projects",
      title1: "Les plus belles résidences",
      title2: "Ils viennent de rejoindre Hoomge",
      title3: "Recherchez le futur appartement de vos rêves",
      title4: "Grâce aux nombreux référencements de projets immobiliers, trouvez le bien qui vous correspond en utilisant les filtres de recherche selon l'appartement et les services dans l'immeuble.",
      main: "Découvrez les projets résidentiels",
      submain: "Faites défiler pour explorer",
      voir: "En savoir plus ",
      projet: "Voir le projet",
      step: "Etape",
      countryFr: "France",
      countryPl: "Pologne",
      search: "Rechercher",
      connect: "Se connecter",
      add: "Ajouter un projet",
      selectacountry: "Sélectionnez un pays",
      selectacity: "Sélectionnez une ville",
      onlyfavorite: "Voir les favoris",
      onlywithgarden: "Avec jardin",
      price: "Prix",
      surface: "Surface",
      chambre: "Chambre",
      residence: "Résidence",
    },
    pl: {
     link: "Zobacz wszystkie projekty",

      title1: "Najpiękniejsze rezydencje",
      title2: "Dołącz do Hoomge",
      title3: "Znajdź przyszłe mieszkanie swoich marzeń",
      title4: "Dzięki licznym projektom mieszkaniowym znajdź mieszkanie, które spełnia Twoje oczekiwania, korzystając z filtrów wyszukiwania według mieszkania i usług w budyn ku.",
      main: "Odkryj projekty mieszkaniowe",
      submain: "Przewiń, aby odkryć",
      voir: "Dowiedz się więcej o ",
      projet: "Zobacz projekt",
      step: "Krok",
      countryFr: "Francja",
      countryPl: "Polska",
      search: "Szukaj",
      connect: "Zaloguj się",
      add: "Dodaj projekt",
      selectacountry: "Wybierz kraj",
      selectacity: "Wybierz miasto",
      onlyfavorite: "Pokaż ulubione",
      onlywithgarden: "Z ogrodem",
      price: "Cena",
      surface: "Powierzchnia",
      chambre: "Pokój",
      residence: "Rezydencja",
     
    },
    en: {
      link: "View all projects",
      title1: "The most beautiful residences",
      title2: "They just joined Hoomge",
      title3: "Find the future apartment of your dreams",
      title4: "Thanks to the numerous real estate projects, find the property that suits you by using the search filters according to the apartment and the services in the building.",
      main: "Discover residential projects",
      submain: "Scroll to explore",
      voir: "Learn more about ",
      projet: "View project",
      step: "Step",
      countryFr: "France",
      countryPl: "Poland",
      search: "Search",
      connect: "Log in",
      add: "Add a project",
      selectacountry: "Select a country",
      selectacity: "Select a city",
      onlyfavorite: "View favorites",
      onlywithgarden: "With garden",
      price: "Price",
      surface: "Surface",
      chambre: "Bedroom",
      residence: "Residence",
    },
    uk: {
      link: "Переглянути всі проекти",
      title1: "Найкрасивіші резиденції",
      title2: "Щойно приєдналися до Hoomge",
      title3: "Знайдіть майбутню квартиру ваших мрій",
      title4: "Завдяки численним проектам нерухомості знайдіть нерухомість, яка вам підходить, використовуючи фільтри пошуку за квартирою та послугами в будівлі.",
      main: "Відкрийте житлові проекти",
      submain: "Прокрутіть, щоб відкрити",
      voir: "Дізнатися більше про ",
      projet: "Переглянути проект",
      step: "Крок",
      countryFr: "Франція",
      countryPl: "Польща",
      search: "Пошук",
      connect: "Увійти",
      add: "Додати проект",
      selectacountry: "Виберіть країну",
      selectacity: "Виберіть місто",
      onlyfavorite: "Переглянути вибрані",
      onlywithgarden: "З садом",
      price: "Ціна",
      surface: "Площа",
      chambre: "Спальня",
      residence: "Резиденція",
    },
  };