export const countryData = {
 
  France: [
    "Agen",
    "Aix-en-Provence",
    "Aix-les-Bains",
    "Ajaccio",
    "Amiens",
    "Angers",
    "Anglet",
    "Angoulême",
    "Annemasse",
    "Annecy",
    "Anzin",
    "Arbonville-lès-Gonesse",
    "Arcueil",
    "Arras",
    "Athis-Mons",
    "Aubervilliers",
    "Avon",
    "Avranches",
    "Bagneux",
    "Bastia",
    "Bayonne",
    "Beaumont",
    "Beaumont-sur-Oise",
    "Beausoleil",
    "Belfort",
    "Bellevue",
    "Béthune",
    "Biarritz",
    "Bordeaux",
    "Boulogne-Billancourt",
    "Boulogne-sur-Mer",
    "Bourg-la-Reine",
    "Bourg-en-Bresse",
    "Brétigny-sur-Orge",
    "Brest",
    "Brunoy",
    "Bry-sur-Marne",
    "Cachan",
    "Cagnes-sur-Mer",
    "Caen",
    "Caluire-et-cuire",
    "Cambrai",
    "Cap-d’Ail",
    "Carrières-sous-Poissy",
    "Carrières-sur-Seine",
    "Castanet-Tolosan",
    "Castelnau-le-Lez",
    "Cesson",
    "Challes-les-eaux",
    "Châlons-en-Champagne",
    "Chalon-sur-Saône",
    "Champigny-sur-Marne",
    "Champs-Sur-Marne",
    "Chaville",
    "Chenôve",
    "Choisy-le-Roi",
    "Clamart",
    "Clermont",
    "Clermont-Ferrand",
    "Clichy",
    "Clichy-sous-Bois",
    "Combs-la-Ville",
    "Conflans-Sainte-Honorine",
    "Courbevoie",
    "Courcouronnes",
    "Créteil",
    "Crégy-lès-Meaux",
    "Dammarie-lè-Lys",
    "Dieppe",
    "Douai",
    "Drancy",
    "Draveil",
    "Dugny",
    "Dunkerque",
    "Échirolles",
    "Élancourt",
    "Enghien-les-Bains",
    "Éragny",
    "Épinay-sous-Sénart",
    "Épinay-sur-Seine",
    "Évian-les-Bains",
    "Évry",
    "Fâches-Thumesnil",
    "Fleury-les-Aubrais",
    "Fleury-Mérogis",
    "Fontaine",
    "Fontaine-lès-Dijon",
    "Fontenay-aux-Roses",
    "Fontenay-le-Fleury",
    "Fontenay-sur-Saône",
    "Fougères",
    "Francheville",
    "Gazainville",
    "Gagny",
    "Garches",
    "Gentilly",
    "Gennevilliers",
    "Grenoble",
    "Grenay",
    "Grigny",
    "Guingamp",
    "Hagondange",
    "Harfleur",
    "Heillecourt",
    "Hendaye",
    "Hœnheim",
    "Houilles",
    "Illzach",
    "Ingénieur",
    "Ivry-sur-Seine",
    "Jacou",
    "Jarville-la-Malgrange",
    "Jouy-le-Moutier",
    "Juvisy-sur-Orge",
    "Kingersheim",
    "La Bassée",
    "La Celle-Saint-Cloud",
    "La Courneuve",
    "La Garde",
    "La Madeleine",
    "La Montagne",
    "La Rochelle",
    "La Salvetat-Saint-Gilles",
    "La Seyne-sur-Mer",
    "La Tour-du-Pin",
    "Laval",
    "Le Portel",
    "Lille",
    "Limay",
    "Limoges",
    "Lorient",
    "L’Haÿ-les-Roses",
    "L’Île-Saint-Denis",
    "Lomme",
    "Longjumeau",
    "Longwy",
    "Lons-le-Saunier",
    "Lormont",
    "Lucé",
    "Lys-lès-Lannoy",
    "Macon",
    "Magnanville",
    "Maisons-Alfort",
    "Maisons-Laffitte",
    "Malakoff",
    "Marquette-lez-Lille",
    "Marseille",
    "Marly",
    "Marly-le-Roi",
    "Maromme",
    "Massy",
    "Meaux",
    "Mérignac",
    "Melun",
    "Menton",
    "Montargis",
    "Montbéliard",
    "Montfermeil",
    "Montgeron",
    "Montluçon",
    "Montpellier",
    "Mont-Saint-Aignan",
    "Montigny-en-Gohelle",
    "Montigny-lès-Cormeilles",
    "Montigny-lès-Metz",
    "Montreuil-sur-Mer",
    "Morlaix",
    "Morangis",
    "Morsang-sur-Orge",
    "Mulhouse",
    "Nancy",
    "Nanterre",
    "Nevers",
    "Neuilly-Plaisance",
    "Neuilly-sur-Marne",
    "Neuilly-sur-Seine",
    "Nîmes",
    "Noyelles-sous-Lens",
    "Oberhausbergen",
    "Oignies",
    "Orléans",
    "Orsay",
    "Outreau",
    "Palaiseau",
    "Palavas-les-Flots",
    "Pau",
    "Pérols",
    "Pessac",
    "Petite-Synthe",
    "Pierre-Bénite",
    "Pierrefitte-sur-Seine",
    "Poitiers",
    "Plaisir",
    "Pont-de-Chéruy",
    "Pont-à-Vendin",
    "Port-Louis",
    "Pusignan",
    "Puteaux",
    "Quincy-sous-Sénart",
    "Ramonville-Saint-Agne",
    "Reims",
    "Rillieux-la-Pape",
    "Ris-Orangis",
    "Roanne",
    "Roissy-en-Brie",
    "Roubaix",
    "Rouen",
    "Rueil-Malmaison",
    "Sablé-sur-Sarthe",
    "Saint-André",
    "Saint-André-de-la-Roche",
    "Saint-Brieuc",
    "Saint-Cyr-l’École",
    "Saint-Denis",
    "Saint-Didier-au-Mont-d’Or",
    "Saint-Étienne",
    "Saint-Étienne-du-Rouvray",
    "Saint-Fons",
    "Saint-Foy-la-Grande",
    "Saint-Genis-Laval",
    "Saint-Genis-Pouilly",
    "Saint-Gratien",
    "Saint-Herblain",
    "Saint-Jean",
    "Saint-Jean-de-Braye",
    "Saint-Jean-de-la-Ruelle",
    "Saint-Laurent-du-Var",
    "Saint-Mandé",
    "Saint-Martin-d’Hères",
    "Saint-Maur-des-Fossés",
    "Saint-Maurice",
    "Saint-Max",
    "Saint-Nazaire",
    "Saint-Ouen",
    "Saint-Ouen-l’Aumône",
    "Saint-Pol-sur-Mer",
    "Saint-Priest",
    "Saint-Priest-en-Jarez",
    "Saint-Sébastien-sur-Loire",
    "Saint-Étienne-du-Rouvray",
    "Sarcelles",
    "Sète",
    "Sevran",
    "Sèvres",
    "Sotteville-lès-Rouen",
    "Sochaux",
    "Soissons",
    "Suresnes",
    "Sucy-en-Brie",
    "Taverny",
    "Talence",
    "Talange",
    "Tarbes",
    "Thonon-les-Bains",
    "Thouars",
    "Toulon",
    "Tours",
    "Tourcoing",
    "Troyes",
    "Trappes",
    "Valence",
    "Valenciennes",
    "Vallauris",
    "Vauréal",
    "Vaux-en-Velin",
    "Vénissieux",
    "Vesoul",
    "Vichy",
    "Ville-d’Avray",
    "Villefranche-sur-Saône",
    "Villejuif",
    "Villemomble",
    "Villeparisis",
    "Villeneuve-Saint-Georges",
    "Villeneuve-la-Garenne",
    "Villeneuve-Tolosane",
    "Villiers-le-Bel",
    "Villiers-sur-Marne",
    "Villiers-sur-Orge",
    "Vincennes",
    "Vitry-le-François",
    "Vitry-sur-Seine",
    "Vivre",
    "Villerupt",
    "Villenave-d’Ornon",
    "Voisins-le-Bretonneux",
    "Wasquehal",
    "Wattignies",
    "Wattrelos",
    "Yvetot",
    "Yerres",
    "Zac",
  ]
  ,
    Polska: [
      "Aleksandrów Kujawski",
      "Aleksandrów Łódzki",
      "Alwernia",
      "Andrychów",
      "Annopol",
      "Augustów",
      "Babimost",
      "Baborów",
      "Baranów Sandomierski",
      "Barcin",
      "Barczewo",
      "Bardo",
      "Barlinek",
      "Bartoszyce",
      "Barwice",
      "Bełchatów",
      "Bełżyce",
      "Biała",
      "Biała Piska",
      "Biała Podlaska",
      "Biała Rawska",
      "Białobrzegi",
      "Białogard",
      "Biały Bór",
      "Białystok",
      "Biecz",
      "Bielawa",
      "Bielsk Podlaski",
      "Bielsko-Biała",
      "Bierutów",
      "Bieruń",
      "Bieżuń",
      "Biskupiec",
      "Bisztynek",
      "Biłgoraj",
      "Blachownia",
      "Bobolice",
      "Bobowa",
      "Bochnia",
      "Bodzentyn",
      "Bogatynia",
      "Boguchwała",
      "Boguszów-Gorce",
      "Bojanowo",
      "Bolesławiec",
      "Bolków",
      "Borek Wielkopolski",
      "Borne Sulinowo",
      "Braniewo",
      "Brańsk",
      "Brodnica",
      "Brok",
      "Brusy",
      "Brwinów",
      "Brzeg",
      "Brzeg Dolny",
      "Brzesko",
      "Brzeszcze",
      "Brzeziny",
      "Brześć Kujawski",
      "Brzostek",
      "Brzozów",
      "Buk",
      "Bukowno",
      "Busko-Zdrój",
      "Bychawa",
      "Byczyna",
      "Bydgoszcz",
      "Bystrzyca Kłodzka",
      "Bytom",
      "Bytom Odrzański",
      "Bytów",
      "Będzin",
      "Błaszki",
      "Błażowa",
      "Błonie",
      "Cedynia",
      "Chełm",
      "Chełmek",
      "Chełmno",
      "Chełmża",
      "Chmielnik",
      "Chocianów",
      "Chociwel",
      "Chocz",
      "Chodecz",
      "Chodzież",
      "Chojna",
      "Chojnice",
      "Chojnów",
      "Choroszcz",
      "Chorzele",
      "Chorzów",
      "Choszczno",
      "Chrzanów",
      "Chęciny",
      "Ciechanowiec",
      "Ciechanów",
      "Ciechocinek",
      "Cieszanów",
      "Cieszyn",
      "Ciężkowice",
      "Cybinka",
      "Czaplinek",
      "Czarna Białostocka",
      "Czarna Woda",
      "Czarne",
      "Czarnków",
      "Czchów",
      "Czechowice-Dziedzice",
      "Czeladź",
      "Czempiń",
      "Czerniejewo",
      "Czersk",
      "Czerwieńsk",
      "Czerwionka-Leszczyny",
      "Czyżew",
      "Częstochowa",
      "Człopa",
      "Człuchów",
      "Daleszyce",
      "Darłowo",
      "Debrzno",
      "Dobczyce",
      "Dobiegniew",
      "Dobra (powiat turecki)",
      "Dobra (powiat łobeski)",
      "Dobre Miasto",
      "Dobrodzień",
      "Dobrzany",
      "Dobrzyca",
      "Dobrzyń nad Wisłą",
      "Dolsk",
      "Drawno",
      "Drawsko Pomorskie",
      "Drezdenko",
      "Drobin",
      "Drohiczyn",
      "Drzewica",
      "Dukla",
      "Duszniki-Zdrój",
      "Dynów",
      "Działdowo",
      "Działoszyce",
      "Działoszyn",
      "Dzierzgoń",
      "Dzierżoniów",
      "Dziwnów",
      "Dąbie",
      "Dąbrowa Białostocka",
      "Dąbrowa Górnicza",
      "Dąbrowa Tarnowska",
      "Dębica",
      "Dęblin",
      "Dębno",
      "Elbląg",
      "Ełk",
      "Frampol",
      "Frombork",
      "Garwolin",
      "Gdańsk",
      "Gdynia",
      "Giżycko",
      "Glinojeck",
      "Gliwice",
      "Gniew",
      "Gniewkowo",
      "Gniezno",
      "Gogolin",
      "Golczewo",
      "Goleniów",
      "Golina",
      "Golub-Dobrzyń",
      "Goniądz",
      "Gorlice",
      "Gorzów Wielkopolski",
      "Gorzów Śląski",
      "Gostynin",
      "Gostyń",
      "Gozdnica",
      "Gołańcz",
      "Gołdap",
      "Gościno",
      "Grabów nad Prosną",
      "Grajewo",
      "Grodków",
      "Grodzisk Mazowiecki",
      "Grodzisk Wielkopolski",
      "Grudziądz",
      "Grybów",
      "Gryfice",
      "Gryfino",
      "Gryfów Śląski",
      "Grójec",
      "Gubin",
      "Góra",
      "Góra Kalwaria",
      "Górowo Iławeckie",
      "Górzno",
      "Gąbin",
      "Głogów",
      "Głogów Małopolski",
      "Głogówek",
      "Głowno",
      "Głubczyce",
      "Głuchołazy",
      "Głuszyca",
      "Główny dworzec kolejowy",
      "Hajnówka",
      "Halinów",
      "Hel",
      "Hrubieszów",
      "Imielin",
      "Inowrocław",
      "Iwonicz-Zdrój",
      "Izbica Kujawska",
      "Iława",
      "Iłowa",
      "Iłża",
      "Ińsko",
      "Jabłonowo Pomorskie",
      "Janikowo",
      "Janowiec Wielkopolski",
      "Janów Lubelski",
      "Jaraczewo",
      "Jarocin",
      "Jarosław",
      "Jasień",
      "Jastarnia",
      "Jastrowie",
      "Jastrzębie-Zdrój",
      "Jasło",
      "Jawor",
      "Jaworzno",
      "Jaworzyna Śląska",
      "Jedlicze",
      "Jedlina-Zdrój",
      "Jedwabne",
      "Jelcz-Laskowice",
      "Jelenia Góra",
      "Jeziorany",
      "Jordanów",
      "Jutrosin",
      "Józefów (powiat biłgorajski)",
      "Józefów (powiat otwocki)",
      "Józefów nad Wisłą",
      "Jędrzejów",
      "Kalety",
      "Kalisz",
      "Kalisz Pomorski",
      "Kalwaria Zebrzydowska",
      "Kamienna Góra",
      "Kamień Krajeński",
      "Kamień Pomorski",
      "Kamieńsk",
      "Karczew",
      "Kargowa",
      "Karlino",
      "Karpacz",
      "Kartuzy",
      "Katowice",
      "Kazimierz Dolny",
      "Kazimierza Wielka",
      "Kałuszyn",
      "Kańczuga",
      "Kcynia",
      "Kielce",
      "Kietrz",
      "Kisielice",
      "Kleczew",
      "Kleszczele",
      "Kluczbork",
      "Knurów",
      "Knyszyn",
      "Kobylin",
      "Kobyłka",
      "Kock",
      "Kolbuszowa",
      "Kolno",
      "Kolonowskie",
      "Koluszki",
      "Koniecpol",
      "Konin",
      "Konstancin-Jeziorna",
      "Konstantynów Łódzki",
      "Koprzywnica",
      "Korfantów",
      "Koronowo",
      "Korsze",
      "Kostrzyn",
      "Kostrzyn nad Odrą",
      "Koszalin",
      "Koszyce",
      "Kosów Lacki",
      "Kowal",
      "Kowalewo Pomorskie",
      "Kowary",
      "Koziegłowy",
      "Kozienice",
      "Kołaczyce",
      "Koło",
      "Kołobrzeg",
      "Końskie",
      "Kościan",
      "Kościerzyna",
      "Koźmin Wielkopolski",
      "Kożuchów",
      "Krajenka",
      "Kraków",
      "Krapkowice",
      "Krasnobród",
      "Krasnystaw",
      "Kraśnik",
      "Krobia",
      "Krosno",
      "Krosno Odrzańskie",
      "Krotoszyn",
      "Krośniewice",
      "Kruszwica",
      "Krynica Morska",
      "Krynica-Zdrój",
      "Krynki",
      "Krzanowice",
      "Krzepice",
      "Krzeszowice",
      "Krzywiń",
      "Krzyż Wielkopolski",
      "Książ Wielkopolski",
      "Kudowa-Zdrój",
      "Kunów",
      "Kutno",
      "Kuźnia Raciborska",
      "Kwidzyn",
      "Kórnik",
      "Kąty Wrocławskie",
      "Kędzierzyn-Koźle",
      "Kępice",
      "Kępno",
      "Kętrzyn",
      "Kęty",
      "Kłecko",
      "Kłobuck",
      "Kłodawa",
      "Kłodzko",
      "Legionowo",
      "Legnica",
      "Lesko",
      "Leszno",
      "Lewin Brzeski",
      "Leśna",
      "Leśnica",
      "Leżajsk",
      "Libiąż",
      "Lidzbark",
      "Lidzbark Warmiński",
      "Limanowa",
      "Lipiany",
      "Lipno",
      "Lipsk",
      "Lipsko",
    
      "Lubaczów",
      "Lubartów",
      "Lubawa",
      "Lubawka",
      "Lubań",
      "Lubień Kujawski",
      "Lubin",
      "Lublin",
      "Lubliniec",
      "Lubniewice",
      "Lubomierz",
      "Lubowidz",
      "Luboń",
      "Lubraniec",
      "Lubsko",
      "Lubycza Królewska",
      "Lwówek",
      "Lwówek Śląski",
      "Lądek-Zdrój",
      "Lębork",
      "Lędziny",
      "Maków Mazowiecki",
      "Maków Podhalański",
      "Malbork",
      "Margonin",
      "Marki",
      "Maszewo",
      "Małogoszcz",
      "Małomice",
      "Miasteczko Śląskie",
      "Miastko",
      "Michałowo",
      "Miechów",
      "Miejska Górka",
      "Mielec",
      "Mielno",
      "Mieroszów",
      "Mieszkowice",
      "Mikołajki",
      "Mikołów",
      "Mikstat",
      "Milanówek",
      "Milicz",
      "Mirosławiec",
      "Mirsk",
      "Międzybórz",
      "Międzychód",
      "Międzylesie",
      "Międzyrzec Podlaski",
      "Międzyrzecz",
      "Międzyzdroje",
      "Miłakowo",
      "Miłomłyn",
      "Miłosław",
      "Mińsk Mazowiecki",
      "Modliborzyce",
      "Mogielnica",
      "Mogilno",
      "Morawica",
      "Mordy",
      "Moryń",
      "Morąg",
      "Mosina",
      "Mońki",
      "Mrocza",
      "Mrozy",
      "Mrągowo",
      "Mszana Dolna",
      "Mszczonów",
      "Murowana Goślina",
      "Muszyna",
      "Myszków",
      "Myszyniec",
      "Mysłowice",
      "Myślenice",
      "Myślibórz",
      "Mława",
      "Młynary",
      "Nakło nad Notecią",
      "Namysłów",
      "Narol",
      "Nasielsk",
      "Nałęczów",
      "Nekla",
      "Nidzica",
      "Niemcza",
      "Niemodlin",
      "Niepołomice",
      "Nieszawa",
      "Nisko",
      "Nowa Dęba",
      "Nowa Ruda",
      "Nowa Sarzyna",
      "Nowa Sól",
      "Nowa Słupia",
      "Nowe",
      "Nowe Brzesko",
      "Nowe Miasteczko",
      "Nowe Miasto Lubawskie",
      "Nowe Miasto nad Pilicą",
      "Nowe Skalmierzyce",
      "Nowe Warpno",
      "Nowogard",
      "Nowogrodziec",
      "Nowogród",
      "Nowogród Bobrzański",
      "Nowy Dwór Gdański",
      "Nowy Dwór Mazowiecki",
      "Nowy Korczyn",
      "Nowy Staw",
      "Nowy Sącz",
      "Nowy Targ",
      "Nowy Tomyśl",
      "Nowy Wiśnicz",
      "Nysa",
      "Oborniki",
      "Oborniki Śląskie",
      "Obrzycko",
      "Odolanów",
      "Ogrodzieniec",
      "Okonek",
      "Olecko",
      "Olesno",
      "Oleszyce",
      "Oleśnica",
      "Olkusz",
      "Olsztyn",
      "Olsztynek",
      "Olszyna",
      "Opalenica",
      "Opatowiec",
      "Opatów",
      "Opatówek",
      "Opoczno",
      "Opole",
      "Opole Lubelskie",
      "Orneta",
      "Orzesze",
      "Orzysz",
      "Osieczna",
      "Osiek",
      "Ostroróg",
      "Ostrowiec Świętokrzyski",
      "Ostrołęka",
      "Ostrzeszów",
      "Ostróda",
      "Ostrów Lubelski",
      "Ostrów Mazowiecka",
      "Ostrów Wielkopolski",
      "Otmuchów",
      "Otwock",
      "Otyń",
      "Ozimek",
      "Ozorków",
      "Oława",
      "Ośno Lubuskie",
      "Oświęcim",
      "Ożarów",
      "Ożarów Mazowiecki",
      "Pabianice",
      "Pacanów",
      "Paczków",
      "Pajęczno",
      "Pakość",
      "Parczew",
      "Pasym",
      "Pasłęk",
      "Pelplin",
      "Pełczyce",
      "Piaseczno",
      "Piaski",
      "Piastów",
      "Piechowice",
      "Piekary Śląskie",
      "Pieniężno",
      "Pierzchnica",
      "Pieszyce",
      "Pieńsk",
      "Pilawa",
      "Pilica",
      "Pilzno",
      "Pionki",
      "Piotrków Kujawski",
      "Piotrków Trybunalski",
      "Pisz",
      "Piwniczna-Zdrój",
      "Piła",
      "Piława Górna",
      "Pińczów",
      "Pleszew",
      "Pniewy",
      "Pobiedziska",
      "Poddębice",
      "Podkowa Leśna",
      "Pogorzela",
      "Polanica-Zdrój",
      "Polanów",
      "Police",
      "Polkowice",
      "Poniatowa",
      "Poniec",
      "Poręba",
      "Poznań",
      "Połaniec",
      "Połczyn-Zdrój",
      "Prabuty",
      "Praszka",
      "Prochowice",
      "Proszowice",
      "Pruchnik",
      "Prudnik",
      "Prusice",
      "Pruszcz Gdański",
      "Pruszków",
      "Przasnysz",
      "Przecław",
      "Przedbórz",
      "Przedecz",
      "Przemków",
      "Przemyśl",
      "Przeworsk",
      "Przysucha",
      "Prószków",
      "Pszczyna",
      "Pszów",
      "Puck",
      "Puszczykowo",
      "Puławy",
      "Pułtusk",
      "Pyrzyce",
      "Pyskowice",
      "Pyzdry",
      "Płock",
      "Płoty",
      "Płońsk",
      "Rabka-Zdrój",
      "Racibórz",
      "Raciąż",
      "Radków",
      "Radlin",
      "Radom",
      "Radomsko",
      "Radomyśl Wielki",
      "Radoszyce",
      "Radymno",
      "Radziejów",
      "Radzionków",
      "Radzymin",
      "Radzyń Chełmiński",
      "Radzyń Podlaski",
      "Radłów",
      "Rajgród",
      "Rakoniewice",
      "Raszków",
      "Ratusz",
      "Rawa Mazowiecka",
      "Rawicz",
      "Recz",
      "Reda",
      "Rejowiec",
      "Rejowiec Fabryczny",
      "Resko",
      "Reszel",
      "Rogoźno",
      "Ropczyce",
      "Ruciane-Nida",
      "Ruda Śląska",
      "Rudnik nad Sanem",
      "Rumia",
      "Rybnik",
      "Rychwał",
      "Rydułtowy",
      "Rydzyna",
      "Ryglice",
      "Ryki",
      "Rymanów",
      "Ryn",
      "Rypin",
      "Rzepin",
      "Rzeszów",
      "Rzgów",
      "Różan",
      "Sandomierz",
      "Sanniki",
      "Sanok",
      "Sejny",
      "Serock",
      "Sianów",
      "Siechnice",
      "Siedlce",
      "Siedliszcze",
      "Siemianowice Śląskie",
      "Siemiatycze",
      "Sieniawa",
      "Sieradz",
      "Sieraków",
      "Sierpc",
      "Siewierz",
      "Skalbmierz",
      "Skarszewy",
      "Skaryszew",
      "Skarżysko-Kamienna",
      "Skawina",
      "Skała",
      "Skierniewice",
      "Skoczów",
      "Skoki",
      "Skwierzyna",
      "Skórcz",
      "Skępe",
      "Sobótka",
      "Sochaczew",
      "Sokołów Małopolski",
      "Sokołów Podlaski",
      "Sokółka",
      "Solec Kujawski",
      "Sompolno",
      "Sopot",
      "Sosnowiec",
      "Sośnicowice",
      "Stalowa Wola",
      "Starachowice",
      "Stargard",
      "Starogard Gdański",
      "Stary Sącz",
      "Staszów",
      "Stawiski",
      "Stawiszyn",
      "Stepnica",
      "Stoczek Łukowski",
      "Stopnica",
      "Stronie Śląskie",
      "Strumień",
      "Stryków",
      "Strzegom",
      "Strzelce Krajeńskie",
      "Strzelce Opolskie",
      "Strzelin",
      "Strzelno",
      "Strzyżów",
      "Stąporków",
      "Stęszew",
      "Sucha Beskidzka",
      "Suchań",
      "Suchedniów",
      "Suchowola",
      "Sulechów",
      "Sulejów",
      "Sulejówek",
      "Sulmierzyce",
      "Sulęcin",
      "Supraśl",
      "Suraż",
      "Susz",
      "Suwałki",
      "Sułkowice",
      "Swarzędz",
      "Syców",
      "Szadek",
      "Szamocin",
      "Szamotuły",
      "Szczawnica",
      "Szczawno-Zdrój",
      "Szczebrzeszyn",
      "Szczecin",
      "Szczecinek",
      "Szczekociny",
      "Szczucin",
      "Szczuczyn",
      "Szczyrk",
      "Szczytna",
      "Szczytno",
      "Szepietowo",
      "Szklarska Poręba",
      "Szlichtyngowa",
      "Szprotawa",
      "Sztum",
      "Szubin",
      "Szydłowiec",
      "Szydłów",
      "Sędziszów",
      "Sędziszów Małopolski",
      "Sępopol",
      "Sępólno Krajeńskie",
      "Sława",
      "Sławków",
      "Sławno",
      "Słomniki",
      "Słubice",
      "Słupca",
      "Słupsk",
      "Tarczyn",
      "Tarnobrzeg",
      "Tarnogród",
      "Tarnowskie Góry",
      "Tarnów",
      "Tczew",
      "Terespol",
      "Tolkmicko",
      "Tomaszów Lubelski",
      "Tomaszów Mazowiecki",
      "Toruń",
      "Torzym",
      "Toszek",
      "Trzcianka",
      "Trzciel",
      "Trzcińsko-Zdrój",
      "Trzebiatów",
      "Trzebinia",
      "Trzebnica",
      "Trzemeszno",
      "Tuchola",
      "Tuchów",
      "Tuczno",
      "Tuliszków",
      "Turek",
      "Tuszyn",
      "Tułowice",
      "Twardogóra",
      "Tychowo",
      "Tychy",
      "Tyczyn",
      "Tykocin",
      "Tyszowce",
      "Tłuszcz",
      "Ujazd",
      "Ujście",
      "Ulanów",
      "Uniejów",
      "Urzędów",
      "Ustka",
      "Ustroń",
      "Ustrzyki Dolne",
      "Wadowice",
      "Warka",
      "Warszawa",
      "Warta",
      "Wasilków",
      "Wałbrzych",
      "Wałcz",
      "Wejherowo",
      "Wielbark",
      "Wieleń",
      "Wielichowo",
      "Wieliczka",
      "Wieluń",
      "Wieruszów",
      "Wilamowice",
      "Wisła",
      "Witkowo",
      "Witnica",
      "Wiązów",
      "Więcbork",
      "Wiślica",
      "Wleń",
      "Wodzisław Śląski",
      "Wojcieszów",
      "Wojkowice",
      "Wojnicz",
      "Wolbrom",
      "Wolbórz",
      "Wolin",
      "Wolsztyn",
      "Wołczyn",
      "Wołomin",
      "Wołów",
      "Woźniki",
      "Wrocław",
      "Wronki",
      "Września",
      "Wschowa",
      "Wyrzysk",
      "Wysoka",
      "Wysokie Mazowieckie",
      "Wyszków",
      "Wyszogród",
      "Wyśmierzyce",
      "Wąbrzeźno",
      "Wąchock",
      "Wągrowiec",
      "Wąsosz",
      "Węgliniec",
      "Węgorzewo",
      "Węgorzyno",
      "Węgrów",
      "Władysławowo",
      "Włocławek",
      "Włodawa",
      "Włoszczowa",
      "Zabrze",
      "Zabłudów",
      "Zagórz",
      "Zagórów",
      "Zakliczyn",
      "Zaklików",
      "Zakopane",
      "Zakroczym",
      "Zalewo",
      "Zambrów",
      "Zamość",
      "Zator",
      "Zawadzkie",
      "Zawichost",
      "Zawidów",
      "Zawiercie",
      "Zbąszynek",
      "Zbąszyń",
      "Zduny",
      "Zduńska Wola",
      "Zdzieszowice",
      "Zelów",
      "Zgierz",
      "Zgorzelec",
      "Zielona Góra",
      "Zielonka",
      "Ziębice",
      "Zwierzyniec",
      "Zwoleń",
      "Ząbki",
      "Ząbkowice Śląskie",
      "Złocieniec",
      "Złoczew",
      "Złotoryja",
      "Złoty Stok",
      "Złotów",
      "Ćmielów",
      "Łabiszyn",
      "Łagów",
      "Łapy",
      "Łasin",
      "Łask",
      "Łaskarzew",
      "Łaszczów",
      "Łaziska Górne",
      "Łazy",
      "Łańcut",
      "Łeba",
      "Łobez",
      "Łobżenica",
      "Łochów",
      "Łomianki",
      "Łomża",
      "Łosice",
      "Łowicz",
      "Łuków",
      "Łódź",
      "Łęczna",
      "Łęczyca",
      "Łęknica",
      "Ścinawa",
      "Ślesin",
      "Śmigiel",
      "Śrem",
      "Środa Wielkopolska",
      "Środa Śląska",
      "Świdnica",
      "Świdnik",
      "Świdwin",
      "Świebodzice",
      "Świebodzin",
      "Świecie",
      "Świeradów-Zdrój",
      "Świerzawa",
      "Świnoujście",
      "Świątniki Górne",
      "Świętochłowice",
      "Żabno",
      "Żagań",
      "Żarki",
      "Żary",
      "Żarów",
      "Żelechów",
      "Żerków",
      "Żmigród",
      "Żnin",
      "Żory",
      "Żukowo",
      "Żuromin",
      "Żychlin",
      "Żyrardów",
      "Żywiec",
    ],
   
  };